language: objective-c
osx_image: xcode11.2
xcode_project: stringcalculator3.xcodeproj
xcode_scheme: stringcalculator3
xcode_sdk: iphonesimulator13.0
script: xcodebuild -project stringcalculator3.xcodeproj -scheme stringcalculator3 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
notifications:
 email: false
